org 0000h

  MOV R0,#0FH   ;DIVIDEND
  MOV R1,#03H   ;DIVISOR
  MOV R7,#00H   ;QUOTIENT
  MOV R4,#00H   ;REMAINDER
  MOV A,R0      ;MOVE DIVIDEND IN A

LOOP:
  SUBB A,R1     ;SUBTRACT THE DIVISOR FROM THE DIVIDEND
  MOV R4,A      ;STORE THE REMAINDER
  JC BREAK      ;IF THE DIVIDEND BECOMES 0, BREAK THE LOOP AND SAVE THE RESULTS
  INC R7        ;STORE THE QUOTIENT
  SJMP LOOP     ;LOOP BACK

BREAK:
  ADD A,R1      ;PUT THE QUOTIENT IN A
  MOV B,A       ;MOVE A INTO B TO SAVE IT
  MOV A,R7      ;PUT THE REMAINDER IN B

END
