MAIN:
  CLR P1.0      ;PORT1.O IS CLEARED SO IS 0
  ACALL DELAY2  ;GO TO DELAY2 FOR CREATE DELAY FOR SIGNAL
  SETB P1.0     ;PORT1.0 BECOMES 1
  MOV TCON,#00H
  ACALL DELAY1  ;GO TO DELAY1 FOR CREATE DELAY FOR SIGNAL 1
  ACALL ENDCODE

WAIT1:
  JNB TF0,WAIT1
  CLR TR0
  CLR TF0
  RET

WAIT2:
  JNB TF0,WAIT2
  CLR TR0
  CLR TF0
  RET

DELAY1:
  MOV TMOD,#01H  ; SELECT MODE OF OPERATION
                 ;COUNT CALCULATED=MAX COUNT(65535) - REQUIRED COUNT(80) + 1
  MOV TL0,#0B0H  ; LOAD LOWER NIBBLE /8BITS IN TL0
  MOV TH0,#0FFH  ;LOAD UPPER NIBBLE /8BITS IN TH0
  MOV TCON,#10H

DELAY2:
  MOV TMOD,#01H  ;SELECT MODE OF OPERATION
                 ;COUNT CALCULATED=MAX COUNT(65535) - REQUIRED COUNT(320) + 1
  MOV TL0,#0C0H  ;LOAD LOWER NIBBLE /8BITS IN TLO
  MOV TH0,#0FEH
  MOV TCON,#10H

ENDCODE:
  END
